[context.production.environment]
  HUGO_VERSION = "0.52"
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL -v"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.52"
[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL -v"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.52"
