[context.production.environment]
  HUGO_VERSION = "0.58.3"
[context.deploy-preview]
  command = "hugo --templateMetrics -F -b $DEPLOY_PRIME_URL -v"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.58.3"
[context.branch-deploy]
  command = "hugo -F -b $DEPLOY_PRIME_URL -v"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.58.3"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
