[context.production.environment]
  HUGO_VERSION = "0.55.0"
[context.deploy-preview]
  command = "hugo -b $URL -v"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.0"
[context.branch-deploy]
  command = "hugo -b $URL -v"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.0"
