name: Letters

on:
  push:
    paths:
      - .github/workflows/letter.yml # Only run a new workflow every time this file (flat.yaml) file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: "*/30 * * * *" # Run this workflow every 5 minutes

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Get API token
        id: get-api-token
        run: |
          token=$(curl 'https://www.italictype.com/api/auth/jwt/create/' \
          -X POST \
          -H 'accept: application/json, text/plain, */*' \
          -H 'content-type: application/json;charset=UTF-8' \
          --data-raw '{"username":"yannick","password":"${{ secrets.ITALICTYPE_PASSWORD }}"}' | jq -r .access)
          echo "::set-output name=italictype_token::${token}"
      - name: Fetch ButtonDown newsletters
        uses: githubocto/flat@v3
        with:
          http_url: "https://api.buttondown.email/v1/emails"
          downloaded_filename: data/newsletter.json
          authorization: "Token ${{ secrets.BUTTONDOWN_API_KEY }}"
          postprocess: flat/buttondown.ts
