name: Liked

on:
  push:
    paths:
      - .github/workflows/liked.yml # Only run a new workflow every time this file (flat.yaml) file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: "0 * * * *" # Run this workflow every 5 minutes

jobs:
  liked:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true
      - name: Fetch liked
        run: |
          bundle exec ruby bin/import-from-arena.rb
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add data/liked.yml
          git add content/bookmarks/images/*
          git commit -m "Sync the liked list" || echo "nothing to do and it is fine"
          git pull origin ${{ github.ref }}
          echo "::set-output name=push::true"
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
